FROM ruby:2.7.2

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y nodejs libpq-dev postgresql-client inotify-tools yarn less && rm -rf /var/lib/apt/lists/

RUN mkdir -p /deploy/tanongsagot
WORKDIR /deploy/tanongsagot

EXPOSE 3000

CMD ["/bin/bash"]
